### ISSUE TITLE
OK, what the hell is going on here?

### ISSUE THREAD

**Issue by GuzioMG** [PatchworkMC/yeet#2]
So basically I just found out about the Patchwork project and went "Oh, cool, I can finally have my favorite Forge Mods and Fabric mods running together!". And then I started going through the GitHub profile to explore the project a bit more. And found this curiosity. "Yeet". No language. No license. Just a description mentioning converting coremods to mixins. So I went ahead and peeked inside. And found precisely nothing and a bit of pure emptiness. So... What the hell is going on here? Did the CM2MIXIN get scrapped? Did it move to base Patchwork? Is it now part of Patchwork-API? It's been over a year since its creation, so I assume 
_something_ must have happened to it... Or did it just got discontinued?

**Comment by TheGlitch76** [comment]
canceled in favor of FUCK, which just loads the coremods directly.
Fabric
Unstable
Coremod
Kit
